//EXAMPLE

export const FRIEND_LOAD = 'FRIEND_LOAD'
export const FRIEND_LOADING = 'FRIEND_LOADING'
// export const SELECT_FRIEND = "SELECT_FRIEND"
export const PENDING_FRIENDS = 'PENDING_FRIENDS'
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND'
export const DENY_FRIEND = 'DENY_FRIEND'
